/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as AuthUserRouteImport } from './routes/auth/user'
import { Route as AuthAdminRouteImport } from './routes/auth/admin'
import { Route as AuthUserIndexRouteImport } from './routes/auth/user/index'
import { Route as AuthAdminIndexRouteImport } from './routes/auth/admin/index'
import { Route as AuthUserLayoutRouteImport } from './routes/auth/user/_layout'
import { Route as AuthAdminLayoutRouteImport } from './routes/auth/admin/_layout'
import { Route as AuthUserLayoutDashboardRouteImport } from './routes/auth/user/_layout/dashboard'
import { Route as AuthAdminLayoutDashboardRouteImport } from './routes/auth/admin/_layout/dashboard'
import { Route as AuthUserLayoutProfileIndexRouteImport } from './routes/auth/user/_layout/profile/index'
import { Route as AuthUserLayoutDashboardIndexRouteImport } from './routes/auth/user/_layout/dashboard/index'
import { Route as AuthAdminLayoutProfileIndexRouteImport } from './routes/auth/admin/_layout/profile/index'
import { Route as AuthAdminLayoutDashboardIndexRouteImport } from './routes/auth/admin/_layout/dashboard/index'
import { Route as AuthUserLayoutDashboardWorkforceRouteImport } from './routes/auth/user/_layout/dashboard/workforce'
import { Route as AuthUserLayoutDashboardTradingRouteImport } from './routes/auth/user/_layout/dashboard/trading'
import { Route as AuthUserLayoutDashboardSalesRouteImport } from './routes/auth/user/_layout/dashboard/sales'
import { Route as AuthUserLayoutDashboardQcRouteImport } from './routes/auth/user/_layout/dashboard/qc'
import { Route as AuthUserLayoutDashboardProductionRouteImport } from './routes/auth/user/_layout/dashboard/production'
import { Route as AuthUserLayoutDashboardProcurementRouteImport } from './routes/auth/user/_layout/dashboard/procurement'
import { Route as AuthUserLayoutDashboardMaintenanceRouteImport } from './routes/auth/user/_layout/dashboard/maintenance'
import { Route as AuthUserLayoutDashboardEnergyRouteImport } from './routes/auth/user/_layout/dashboard/energy'
import { Route as AuthUserLayoutDashboardAccountsRouteImport } from './routes/auth/user/_layout/dashboard/accounts'
import { Route as AuthAdminLayoutDashboardWorkforceRouteImport } from './routes/auth/admin/_layout/dashboard/workforce'
import { Route as AuthAdminLayoutDashboardTradingRouteImport } from './routes/auth/admin/_layout/dashboard/trading'
import { Route as AuthAdminLayoutDashboardSalesRouteImport } from './routes/auth/admin/_layout/dashboard/sales'
import { Route as AuthAdminLayoutDashboardQcRouteImport } from './routes/auth/admin/_layout/dashboard/qc'
import { Route as AuthAdminLayoutDashboardProductionRouteImport } from './routes/auth/admin/_layout/dashboard/production'
import { Route as AuthAdminLayoutDashboardProcurementRouteImport } from './routes/auth/admin/_layout/dashboard/procurement'
import { Route as AuthAdminLayoutDashboardMaintenanceRouteImport } from './routes/auth/admin/_layout/dashboard/maintenance'
import { Route as AuthAdminLayoutDashboardEnergyRouteImport } from './routes/auth/admin/_layout/dashboard/energy'
import { Route as AuthAdminLayoutDashboardAccountsRouteImport } from './routes/auth/admin/_layout/dashboard/accounts'
import { Route as AuthUserLayoutProfileSettingsIndexRouteImport } from './routes/auth/user/_layout/profile/settings/index'
import { Route as AuthAdminLayoutProfileUsersIndexRouteImport } from './routes/auth/admin/_layout/profile/users/index'
import { Route as AuthAdminLayoutProfileSettingsIndexRouteImport } from './routes/auth/admin/_layout/profile/settings/index'
import { Route as AuthAdminLayoutProfileLogIndexRouteImport } from './routes/auth/admin/_layout/profile/log/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUserRoute = AuthUserRouteImport.update({
  id: '/auth/user',
  path: '/auth/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUserIndexRoute = AuthUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthUserRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthUserLayoutRoute = AuthUserLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthUserRoute,
} as any)
const AuthAdminLayoutRoute = AuthAdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthUserLayoutDashboardRoute = AuthUserLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthUserLayoutRoute,
} as any)
const AuthAdminLayoutDashboardRoute =
  AuthAdminLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthAdminLayoutRoute,
  } as any)
const AuthUserLayoutProfileIndexRoute =
  AuthUserLayoutProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthUserLayoutRoute,
  } as any)
const AuthUserLayoutDashboardIndexRoute =
  AuthUserLayoutDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthUserLayoutDashboardRoute,
  } as any)
const AuthAdminLayoutProfileIndexRoute =
  AuthAdminLayoutProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthAdminLayoutRoute,
  } as any)
const AuthAdminLayoutDashboardIndexRoute =
  AuthAdminLayoutDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthAdminLayoutDashboardRoute,
  } as any)
const AuthUserLayoutDashboardWorkforceRoute =
  AuthUserLayoutDashboardWorkforceRouteImport.update({
    id: '/workforce',
    path: '/workforce',
    getParentRoute: () => AuthUserLayoutDashboardRoute,
  } as any)
const AuthUserLayoutDashboardTradingRoute =
  AuthUserLayoutDashboardTradingRouteImport.update({
    id: '/trading',
    path: '/trading',
    getParentRoute: () => AuthUserLayoutDashboardRoute,
  } as any)
const AuthUserLayoutDashboardSalesRoute =
  AuthUserLayoutDashboardSalesRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => AuthUserLayoutDashboardRoute,
  } as any)
const AuthUserLayoutDashboardQcRoute =
  AuthUserLayoutDashboardQcRouteImport.update({
    id: '/qc',
    path: '/qc',
    getParentRoute: () => AuthUserLayoutDashboardRoute,
  } as any)
const AuthUserLayoutDashboardProductionRoute =
  AuthUserLayoutDashboardProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthUserLayoutDashboardRoute,
  } as any)
const AuthUserLayoutDashboardProcurementRoute =
  AuthUserLayoutDashboardProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthUserLayoutDashboardRoute,
  } as any)
const AuthUserLayoutDashboardMaintenanceRoute =
  AuthUserLayoutDashboardMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthUserLayoutDashboardRoute,
  } as any)
const AuthUserLayoutDashboardEnergyRoute =
  AuthUserLayoutDashboardEnergyRouteImport.update({
    id: '/energy',
    path: '/energy',
    getParentRoute: () => AuthUserLayoutDashboardRoute,
  } as any)
const AuthUserLayoutDashboardAccountsRoute =
  AuthUserLayoutDashboardAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthUserLayoutDashboardRoute,
  } as any)
const AuthAdminLayoutDashboardWorkforceRoute =
  AuthAdminLayoutDashboardWorkforceRouteImport.update({
    id: '/workforce',
    path: '/workforce',
    getParentRoute: () => AuthAdminLayoutDashboardRoute,
  } as any)
const AuthAdminLayoutDashboardTradingRoute =
  AuthAdminLayoutDashboardTradingRouteImport.update({
    id: '/trading',
    path: '/trading',
    getParentRoute: () => AuthAdminLayoutDashboardRoute,
  } as any)
const AuthAdminLayoutDashboardSalesRoute =
  AuthAdminLayoutDashboardSalesRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => AuthAdminLayoutDashboardRoute,
  } as any)
const AuthAdminLayoutDashboardQcRoute =
  AuthAdminLayoutDashboardQcRouteImport.update({
    id: '/qc',
    path: '/qc',
    getParentRoute: () => AuthAdminLayoutDashboardRoute,
  } as any)
const AuthAdminLayoutDashboardProductionRoute =
  AuthAdminLayoutDashboardProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthAdminLayoutDashboardRoute,
  } as any)
const AuthAdminLayoutDashboardProcurementRoute =
  AuthAdminLayoutDashboardProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthAdminLayoutDashboardRoute,
  } as any)
const AuthAdminLayoutDashboardMaintenanceRoute =
  AuthAdminLayoutDashboardMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthAdminLayoutDashboardRoute,
  } as any)
const AuthAdminLayoutDashboardEnergyRoute =
  AuthAdminLayoutDashboardEnergyRouteImport.update({
    id: '/energy',
    path: '/energy',
    getParentRoute: () => AuthAdminLayoutDashboardRoute,
  } as any)
const AuthAdminLayoutDashboardAccountsRoute =
  AuthAdminLayoutDashboardAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthAdminLayoutDashboardRoute,
  } as any)
const AuthUserLayoutProfileSettingsIndexRoute =
  AuthUserLayoutProfileSettingsIndexRouteImport.update({
    id: '/profile/settings/',
    path: '/profile/settings/',
    getParentRoute: () => AuthUserLayoutRoute,
  } as any)
const AuthAdminLayoutProfileUsersIndexRoute =
  AuthAdminLayoutProfileUsersIndexRouteImport.update({
    id: '/profile/users/',
    path: '/profile/users/',
    getParentRoute: () => AuthAdminLayoutRoute,
  } as any)
const AuthAdminLayoutProfileSettingsIndexRoute =
  AuthAdminLayoutProfileSettingsIndexRouteImport.update({
    id: '/profile/settings/',
    path: '/profile/settings/',
    getParentRoute: () => AuthAdminLayoutRoute,
  } as any)
const AuthAdminLayoutProfileLogIndexRoute =
  AuthAdminLayoutProfileLogIndexRouteImport.update({
    id: '/profile/log/',
    path: '/profile/log/',
    getParentRoute: () => AuthAdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/admin': typeof AuthAdminLayoutRouteWithChildren
  '/auth/user': typeof AuthUserLayoutRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/admin/': typeof AuthAdminIndexRoute
  '/auth/user/': typeof AuthUserIndexRoute
  '/auth/admin/dashboard': typeof AuthAdminLayoutDashboardRouteWithChildren
  '/auth/user/dashboard': typeof AuthUserLayoutDashboardRouteWithChildren
  '/auth/admin/dashboard/accounts': typeof AuthAdminLayoutDashboardAccountsRoute
  '/auth/admin/dashboard/energy': typeof AuthAdminLayoutDashboardEnergyRoute
  '/auth/admin/dashboard/maintenance': typeof AuthAdminLayoutDashboardMaintenanceRoute
  '/auth/admin/dashboard/procurement': typeof AuthAdminLayoutDashboardProcurementRoute
  '/auth/admin/dashboard/production': typeof AuthAdminLayoutDashboardProductionRoute
  '/auth/admin/dashboard/qc': typeof AuthAdminLayoutDashboardQcRoute
  '/auth/admin/dashboard/sales': typeof AuthAdminLayoutDashboardSalesRoute
  '/auth/admin/dashboard/trading': typeof AuthAdminLayoutDashboardTradingRoute
  '/auth/admin/dashboard/workforce': typeof AuthAdminLayoutDashboardWorkforceRoute
  '/auth/user/dashboard/accounts': typeof AuthUserLayoutDashboardAccountsRoute
  '/auth/user/dashboard/energy': typeof AuthUserLayoutDashboardEnergyRoute
  '/auth/user/dashboard/maintenance': typeof AuthUserLayoutDashboardMaintenanceRoute
  '/auth/user/dashboard/procurement': typeof AuthUserLayoutDashboardProcurementRoute
  '/auth/user/dashboard/production': typeof AuthUserLayoutDashboardProductionRoute
  '/auth/user/dashboard/qc': typeof AuthUserLayoutDashboardQcRoute
  '/auth/user/dashboard/sales': typeof AuthUserLayoutDashboardSalesRoute
  '/auth/user/dashboard/trading': typeof AuthUserLayoutDashboardTradingRoute
  '/auth/user/dashboard/workforce': typeof AuthUserLayoutDashboardWorkforceRoute
  '/auth/admin/dashboard/': typeof AuthAdminLayoutDashboardIndexRoute
  '/auth/admin/profile/': typeof AuthAdminLayoutProfileIndexRoute
  '/auth/user/dashboard/': typeof AuthUserLayoutDashboardIndexRoute
  '/auth/user/profile/': typeof AuthUserLayoutProfileIndexRoute
  '/auth/admin/profile/log/': typeof AuthAdminLayoutProfileLogIndexRoute
  '/auth/admin/profile/settings/': typeof AuthAdminLayoutProfileSettingsIndexRoute
  '/auth/admin/profile/users/': typeof AuthAdminLayoutProfileUsersIndexRoute
  '/auth/user/profile/settings/': typeof AuthUserLayoutProfileSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/admin': typeof AuthAdminIndexRoute
  '/auth/user': typeof AuthUserIndexRoute
  '/auth/admin/dashboard/accounts': typeof AuthAdminLayoutDashboardAccountsRoute
  '/auth/admin/dashboard/energy': typeof AuthAdminLayoutDashboardEnergyRoute
  '/auth/admin/dashboard/maintenance': typeof AuthAdminLayoutDashboardMaintenanceRoute
  '/auth/admin/dashboard/procurement': typeof AuthAdminLayoutDashboardProcurementRoute
  '/auth/admin/dashboard/production': typeof AuthAdminLayoutDashboardProductionRoute
  '/auth/admin/dashboard/qc': typeof AuthAdminLayoutDashboardQcRoute
  '/auth/admin/dashboard/sales': typeof AuthAdminLayoutDashboardSalesRoute
  '/auth/admin/dashboard/trading': typeof AuthAdminLayoutDashboardTradingRoute
  '/auth/admin/dashboard/workforce': typeof AuthAdminLayoutDashboardWorkforceRoute
  '/auth/user/dashboard/accounts': typeof AuthUserLayoutDashboardAccountsRoute
  '/auth/user/dashboard/energy': typeof AuthUserLayoutDashboardEnergyRoute
  '/auth/user/dashboard/maintenance': typeof AuthUserLayoutDashboardMaintenanceRoute
  '/auth/user/dashboard/procurement': typeof AuthUserLayoutDashboardProcurementRoute
  '/auth/user/dashboard/production': typeof AuthUserLayoutDashboardProductionRoute
  '/auth/user/dashboard/qc': typeof AuthUserLayoutDashboardQcRoute
  '/auth/user/dashboard/sales': typeof AuthUserLayoutDashboardSalesRoute
  '/auth/user/dashboard/trading': typeof AuthUserLayoutDashboardTradingRoute
  '/auth/user/dashboard/workforce': typeof AuthUserLayoutDashboardWorkforceRoute
  '/auth/admin/dashboard': typeof AuthAdminLayoutDashboardIndexRoute
  '/auth/admin/profile': typeof AuthAdminLayoutProfileIndexRoute
  '/auth/user/dashboard': typeof AuthUserLayoutDashboardIndexRoute
  '/auth/user/profile': typeof AuthUserLayoutProfileIndexRoute
  '/auth/admin/profile/log': typeof AuthAdminLayoutProfileLogIndexRoute
  '/auth/admin/profile/settings': typeof AuthAdminLayoutProfileSettingsIndexRoute
  '/auth/admin/profile/users': typeof AuthAdminLayoutProfileUsersIndexRoute
  '/auth/user/profile/settings': typeof AuthUserLayoutProfileSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/admin': typeof AuthAdminRouteWithChildren
  '/auth/user': typeof AuthUserRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/admin/_layout': typeof AuthAdminLayoutRouteWithChildren
  '/auth/user/_layout': typeof AuthUserLayoutRouteWithChildren
  '/auth/admin/': typeof AuthAdminIndexRoute
  '/auth/user/': typeof AuthUserIndexRoute
  '/auth/admin/_layout/dashboard': typeof AuthAdminLayoutDashboardRouteWithChildren
  '/auth/user/_layout/dashboard': typeof AuthUserLayoutDashboardRouteWithChildren
  '/auth/admin/_layout/dashboard/accounts': typeof AuthAdminLayoutDashboardAccountsRoute
  '/auth/admin/_layout/dashboard/energy': typeof AuthAdminLayoutDashboardEnergyRoute
  '/auth/admin/_layout/dashboard/maintenance': typeof AuthAdminLayoutDashboardMaintenanceRoute
  '/auth/admin/_layout/dashboard/procurement': typeof AuthAdminLayoutDashboardProcurementRoute
  '/auth/admin/_layout/dashboard/production': typeof AuthAdminLayoutDashboardProductionRoute
  '/auth/admin/_layout/dashboard/qc': typeof AuthAdminLayoutDashboardQcRoute
  '/auth/admin/_layout/dashboard/sales': typeof AuthAdminLayoutDashboardSalesRoute
  '/auth/admin/_layout/dashboard/trading': typeof AuthAdminLayoutDashboardTradingRoute
  '/auth/admin/_layout/dashboard/workforce': typeof AuthAdminLayoutDashboardWorkforceRoute
  '/auth/user/_layout/dashboard/accounts': typeof AuthUserLayoutDashboardAccountsRoute
  '/auth/user/_layout/dashboard/energy': typeof AuthUserLayoutDashboardEnergyRoute
  '/auth/user/_layout/dashboard/maintenance': typeof AuthUserLayoutDashboardMaintenanceRoute
  '/auth/user/_layout/dashboard/procurement': typeof AuthUserLayoutDashboardProcurementRoute
  '/auth/user/_layout/dashboard/production': typeof AuthUserLayoutDashboardProductionRoute
  '/auth/user/_layout/dashboard/qc': typeof AuthUserLayoutDashboardQcRoute
  '/auth/user/_layout/dashboard/sales': typeof AuthUserLayoutDashboardSalesRoute
  '/auth/user/_layout/dashboard/trading': typeof AuthUserLayoutDashboardTradingRoute
  '/auth/user/_layout/dashboard/workforce': typeof AuthUserLayoutDashboardWorkforceRoute
  '/auth/admin/_layout/dashboard/': typeof AuthAdminLayoutDashboardIndexRoute
  '/auth/admin/_layout/profile/': typeof AuthAdminLayoutProfileIndexRoute
  '/auth/user/_layout/dashboard/': typeof AuthUserLayoutDashboardIndexRoute
  '/auth/user/_layout/profile/': typeof AuthUserLayoutProfileIndexRoute
  '/auth/admin/_layout/profile/log/': typeof AuthAdminLayoutProfileLogIndexRoute
  '/auth/admin/_layout/profile/settings/': typeof AuthAdminLayoutProfileSettingsIndexRoute
  '/auth/admin/_layout/profile/users/': typeof AuthAdminLayoutProfileUsersIndexRoute
  '/auth/user/_layout/profile/settings/': typeof AuthUserLayoutProfileSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/admin'
    | '/auth/user'
    | '/dashboard/settings'
    | '/auth/'
    | '/dashboard/'
    | '/auth/admin/'
    | '/auth/user/'
    | '/auth/admin/dashboard'
    | '/auth/user/dashboard'
    | '/auth/admin/dashboard/accounts'
    | '/auth/admin/dashboard/energy'
    | '/auth/admin/dashboard/maintenance'
    | '/auth/admin/dashboard/procurement'
    | '/auth/admin/dashboard/production'
    | '/auth/admin/dashboard/qc'
    | '/auth/admin/dashboard/sales'
    | '/auth/admin/dashboard/trading'
    | '/auth/admin/dashboard/workforce'
    | '/auth/user/dashboard/accounts'
    | '/auth/user/dashboard/energy'
    | '/auth/user/dashboard/maintenance'
    | '/auth/user/dashboard/procurement'
    | '/auth/user/dashboard/production'
    | '/auth/user/dashboard/qc'
    | '/auth/user/dashboard/sales'
    | '/auth/user/dashboard/trading'
    | '/auth/user/dashboard/workforce'
    | '/auth/admin/dashboard/'
    | '/auth/admin/profile/'
    | '/auth/user/dashboard/'
    | '/auth/user/profile/'
    | '/auth/admin/profile/log/'
    | '/auth/admin/profile/settings/'
    | '/auth/admin/profile/users/'
    | '/auth/user/profile/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/settings'
    | '/auth'
    | '/dashboard'
    | '/auth/admin'
    | '/auth/user'
    | '/auth/admin/dashboard/accounts'
    | '/auth/admin/dashboard/energy'
    | '/auth/admin/dashboard/maintenance'
    | '/auth/admin/dashboard/procurement'
    | '/auth/admin/dashboard/production'
    | '/auth/admin/dashboard/qc'
    | '/auth/admin/dashboard/sales'
    | '/auth/admin/dashboard/trading'
    | '/auth/admin/dashboard/workforce'
    | '/auth/user/dashboard/accounts'
    | '/auth/user/dashboard/energy'
    | '/auth/user/dashboard/maintenance'
    | '/auth/user/dashboard/procurement'
    | '/auth/user/dashboard/production'
    | '/auth/user/dashboard/qc'
    | '/auth/user/dashboard/sales'
    | '/auth/user/dashboard/trading'
    | '/auth/user/dashboard/workforce'
    | '/auth/admin/dashboard'
    | '/auth/admin/profile'
    | '/auth/user/dashboard'
    | '/auth/user/profile'
    | '/auth/admin/profile/log'
    | '/auth/admin/profile/settings'
    | '/auth/admin/profile/users'
    | '/auth/user/profile/settings'
  id:
    | '__root__'
    | '/'
    | '/auth/admin'
    | '/auth/user'
    | '/dashboard/settings'
    | '/auth/'
    | '/dashboard/'
    | '/auth/admin/_layout'
    | '/auth/user/_layout'
    | '/auth/admin/'
    | '/auth/user/'
    | '/auth/admin/_layout/dashboard'
    | '/auth/user/_layout/dashboard'
    | '/auth/admin/_layout/dashboard/accounts'
    | '/auth/admin/_layout/dashboard/energy'
    | '/auth/admin/_layout/dashboard/maintenance'
    | '/auth/admin/_layout/dashboard/procurement'
    | '/auth/admin/_layout/dashboard/production'
    | '/auth/admin/_layout/dashboard/qc'
    | '/auth/admin/_layout/dashboard/sales'
    | '/auth/admin/_layout/dashboard/trading'
    | '/auth/admin/_layout/dashboard/workforce'
    | '/auth/user/_layout/dashboard/accounts'
    | '/auth/user/_layout/dashboard/energy'
    | '/auth/user/_layout/dashboard/maintenance'
    | '/auth/user/_layout/dashboard/procurement'
    | '/auth/user/_layout/dashboard/production'
    | '/auth/user/_layout/dashboard/qc'
    | '/auth/user/_layout/dashboard/sales'
    | '/auth/user/_layout/dashboard/trading'
    | '/auth/user/_layout/dashboard/workforce'
    | '/auth/admin/_layout/dashboard/'
    | '/auth/admin/_layout/profile/'
    | '/auth/user/_layout/dashboard/'
    | '/auth/user/_layout/profile/'
    | '/auth/admin/_layout/profile/log/'
    | '/auth/admin/_layout/profile/settings/'
    | '/auth/admin/_layout/profile/users/'
    | '/auth/user/_layout/profile/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthUserRoute: typeof AuthUserRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/user': {
      id: '/auth/user'
      path: '/auth/user'
      fullPath: '/auth/user'
      preLoaderRoute: typeof AuthUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/user/': {
      id: '/auth/user/'
      path: '/'
      fullPath: '/auth/user/'
      preLoaderRoute: typeof AuthUserIndexRouteImport
      parentRoute: typeof AuthUserRoute
    }
    '/auth/admin/': {
      id: '/auth/admin/'
      path: '/'
      fullPath: '/auth/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/auth/user/_layout': {
      id: '/auth/user/_layout'
      path: ''
      fullPath: '/auth/user'
      preLoaderRoute: typeof AuthUserLayoutRouteImport
      parentRoute: typeof AuthUserRoute
    }
    '/auth/admin/_layout': {
      id: '/auth/admin/_layout'
      path: ''
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminLayoutRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/auth/user/_layout/dashboard': {
      id: '/auth/user/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/auth/user/dashboard'
      preLoaderRoute: typeof AuthUserLayoutDashboardRouteImport
      parentRoute: typeof AuthUserLayoutRoute
    }
    '/auth/admin/_layout/dashboard': {
      id: '/auth/admin/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/auth/admin/dashboard'
      preLoaderRoute: typeof AuthAdminLayoutDashboardRouteImport
      parentRoute: typeof AuthAdminLayoutRoute
    }
    '/auth/user/_layout/profile/': {
      id: '/auth/user/_layout/profile/'
      path: '/profile'
      fullPath: '/auth/user/profile/'
      preLoaderRoute: typeof AuthUserLayoutProfileIndexRouteImport
      parentRoute: typeof AuthUserLayoutRoute
    }
    '/auth/user/_layout/dashboard/': {
      id: '/auth/user/_layout/dashboard/'
      path: '/'
      fullPath: '/auth/user/dashboard/'
      preLoaderRoute: typeof AuthUserLayoutDashboardIndexRouteImport
      parentRoute: typeof AuthUserLayoutDashboardRoute
    }
    '/auth/admin/_layout/profile/': {
      id: '/auth/admin/_layout/profile/'
      path: '/profile'
      fullPath: '/auth/admin/profile/'
      preLoaderRoute: typeof AuthAdminLayoutProfileIndexRouteImport
      parentRoute: typeof AuthAdminLayoutRoute
    }
    '/auth/admin/_layout/dashboard/': {
      id: '/auth/admin/_layout/dashboard/'
      path: '/'
      fullPath: '/auth/admin/dashboard/'
      preLoaderRoute: typeof AuthAdminLayoutDashboardIndexRouteImport
      parentRoute: typeof AuthAdminLayoutDashboardRoute
    }
    '/auth/user/_layout/dashboard/workforce': {
      id: '/auth/user/_layout/dashboard/workforce'
      path: '/workforce'
      fullPath: '/auth/user/dashboard/workforce'
      preLoaderRoute: typeof AuthUserLayoutDashboardWorkforceRouteImport
      parentRoute: typeof AuthUserLayoutDashboardRoute
    }
    '/auth/user/_layout/dashboard/trading': {
      id: '/auth/user/_layout/dashboard/trading'
      path: '/trading'
      fullPath: '/auth/user/dashboard/trading'
      preLoaderRoute: typeof AuthUserLayoutDashboardTradingRouteImport
      parentRoute: typeof AuthUserLayoutDashboardRoute
    }
    '/auth/user/_layout/dashboard/sales': {
      id: '/auth/user/_layout/dashboard/sales'
      path: '/sales'
      fullPath: '/auth/user/dashboard/sales'
      preLoaderRoute: typeof AuthUserLayoutDashboardSalesRouteImport
      parentRoute: typeof AuthUserLayoutDashboardRoute
    }
    '/auth/user/_layout/dashboard/qc': {
      id: '/auth/user/_layout/dashboard/qc'
      path: '/qc'
      fullPath: '/auth/user/dashboard/qc'
      preLoaderRoute: typeof AuthUserLayoutDashboardQcRouteImport
      parentRoute: typeof AuthUserLayoutDashboardRoute
    }
    '/auth/user/_layout/dashboard/production': {
      id: '/auth/user/_layout/dashboard/production'
      path: '/production'
      fullPath: '/auth/user/dashboard/production'
      preLoaderRoute: typeof AuthUserLayoutDashboardProductionRouteImport
      parentRoute: typeof AuthUserLayoutDashboardRoute
    }
    '/auth/user/_layout/dashboard/procurement': {
      id: '/auth/user/_layout/dashboard/procurement'
      path: '/procurement'
      fullPath: '/auth/user/dashboard/procurement'
      preLoaderRoute: typeof AuthUserLayoutDashboardProcurementRouteImport
      parentRoute: typeof AuthUserLayoutDashboardRoute
    }
    '/auth/user/_layout/dashboard/maintenance': {
      id: '/auth/user/_layout/dashboard/maintenance'
      path: '/maintenance'
      fullPath: '/auth/user/dashboard/maintenance'
      preLoaderRoute: typeof AuthUserLayoutDashboardMaintenanceRouteImport
      parentRoute: typeof AuthUserLayoutDashboardRoute
    }
    '/auth/user/_layout/dashboard/energy': {
      id: '/auth/user/_layout/dashboard/energy'
      path: '/energy'
      fullPath: '/auth/user/dashboard/energy'
      preLoaderRoute: typeof AuthUserLayoutDashboardEnergyRouteImport
      parentRoute: typeof AuthUserLayoutDashboardRoute
    }
    '/auth/user/_layout/dashboard/accounts': {
      id: '/auth/user/_layout/dashboard/accounts'
      path: '/accounts'
      fullPath: '/auth/user/dashboard/accounts'
      preLoaderRoute: typeof AuthUserLayoutDashboardAccountsRouteImport
      parentRoute: typeof AuthUserLayoutDashboardRoute
    }
    '/auth/admin/_layout/dashboard/workforce': {
      id: '/auth/admin/_layout/dashboard/workforce'
      path: '/workforce'
      fullPath: '/auth/admin/dashboard/workforce'
      preLoaderRoute: typeof AuthAdminLayoutDashboardWorkforceRouteImport
      parentRoute: typeof AuthAdminLayoutDashboardRoute
    }
    '/auth/admin/_layout/dashboard/trading': {
      id: '/auth/admin/_layout/dashboard/trading'
      path: '/trading'
      fullPath: '/auth/admin/dashboard/trading'
      preLoaderRoute: typeof AuthAdminLayoutDashboardTradingRouteImport
      parentRoute: typeof AuthAdminLayoutDashboardRoute
    }
    '/auth/admin/_layout/dashboard/sales': {
      id: '/auth/admin/_layout/dashboard/sales'
      path: '/sales'
      fullPath: '/auth/admin/dashboard/sales'
      preLoaderRoute: typeof AuthAdminLayoutDashboardSalesRouteImport
      parentRoute: typeof AuthAdminLayoutDashboardRoute
    }
    '/auth/admin/_layout/dashboard/qc': {
      id: '/auth/admin/_layout/dashboard/qc'
      path: '/qc'
      fullPath: '/auth/admin/dashboard/qc'
      preLoaderRoute: typeof AuthAdminLayoutDashboardQcRouteImport
      parentRoute: typeof AuthAdminLayoutDashboardRoute
    }
    '/auth/admin/_layout/dashboard/production': {
      id: '/auth/admin/_layout/dashboard/production'
      path: '/production'
      fullPath: '/auth/admin/dashboard/production'
      preLoaderRoute: typeof AuthAdminLayoutDashboardProductionRouteImport
      parentRoute: typeof AuthAdminLayoutDashboardRoute
    }
    '/auth/admin/_layout/dashboard/procurement': {
      id: '/auth/admin/_layout/dashboard/procurement'
      path: '/procurement'
      fullPath: '/auth/admin/dashboard/procurement'
      preLoaderRoute: typeof AuthAdminLayoutDashboardProcurementRouteImport
      parentRoute: typeof AuthAdminLayoutDashboardRoute
    }
    '/auth/admin/_layout/dashboard/maintenance': {
      id: '/auth/admin/_layout/dashboard/maintenance'
      path: '/maintenance'
      fullPath: '/auth/admin/dashboard/maintenance'
      preLoaderRoute: typeof AuthAdminLayoutDashboardMaintenanceRouteImport
      parentRoute: typeof AuthAdminLayoutDashboardRoute
    }
    '/auth/admin/_layout/dashboard/energy': {
      id: '/auth/admin/_layout/dashboard/energy'
      path: '/energy'
      fullPath: '/auth/admin/dashboard/energy'
      preLoaderRoute: typeof AuthAdminLayoutDashboardEnergyRouteImport
      parentRoute: typeof AuthAdminLayoutDashboardRoute
    }
    '/auth/admin/_layout/dashboard/accounts': {
      id: '/auth/admin/_layout/dashboard/accounts'
      path: '/accounts'
      fullPath: '/auth/admin/dashboard/accounts'
      preLoaderRoute: typeof AuthAdminLayoutDashboardAccountsRouteImport
      parentRoute: typeof AuthAdminLayoutDashboardRoute
    }
    '/auth/user/_layout/profile/settings/': {
      id: '/auth/user/_layout/profile/settings/'
      path: '/profile/settings'
      fullPath: '/auth/user/profile/settings/'
      preLoaderRoute: typeof AuthUserLayoutProfileSettingsIndexRouteImport
      parentRoute: typeof AuthUserLayoutRoute
    }
    '/auth/admin/_layout/profile/users/': {
      id: '/auth/admin/_layout/profile/users/'
      path: '/profile/users'
      fullPath: '/auth/admin/profile/users/'
      preLoaderRoute: typeof AuthAdminLayoutProfileUsersIndexRouteImport
      parentRoute: typeof AuthAdminLayoutRoute
    }
    '/auth/admin/_layout/profile/settings/': {
      id: '/auth/admin/_layout/profile/settings/'
      path: '/profile/settings'
      fullPath: '/auth/admin/profile/settings/'
      preLoaderRoute: typeof AuthAdminLayoutProfileSettingsIndexRouteImport
      parentRoute: typeof AuthAdminLayoutRoute
    }
    '/auth/admin/_layout/profile/log/': {
      id: '/auth/admin/_layout/profile/log/'
      path: '/profile/log'
      fullPath: '/auth/admin/profile/log/'
      preLoaderRoute: typeof AuthAdminLayoutProfileLogIndexRouteImport
      parentRoute: typeof AuthAdminLayoutRoute
    }
  }
}

interface AuthAdminLayoutDashboardRouteChildren {
  AuthAdminLayoutDashboardAccountsRoute: typeof AuthAdminLayoutDashboardAccountsRoute
  AuthAdminLayoutDashboardEnergyRoute: typeof AuthAdminLayoutDashboardEnergyRoute
  AuthAdminLayoutDashboardMaintenanceRoute: typeof AuthAdminLayoutDashboardMaintenanceRoute
  AuthAdminLayoutDashboardProcurementRoute: typeof AuthAdminLayoutDashboardProcurementRoute
  AuthAdminLayoutDashboardProductionRoute: typeof AuthAdminLayoutDashboardProductionRoute
  AuthAdminLayoutDashboardQcRoute: typeof AuthAdminLayoutDashboardQcRoute
  AuthAdminLayoutDashboardSalesRoute: typeof AuthAdminLayoutDashboardSalesRoute
  AuthAdminLayoutDashboardTradingRoute: typeof AuthAdminLayoutDashboardTradingRoute
  AuthAdminLayoutDashboardWorkforceRoute: typeof AuthAdminLayoutDashboardWorkforceRoute
  AuthAdminLayoutDashboardIndexRoute: typeof AuthAdminLayoutDashboardIndexRoute
}

const AuthAdminLayoutDashboardRouteChildren: AuthAdminLayoutDashboardRouteChildren =
  {
    AuthAdminLayoutDashboardAccountsRoute:
      AuthAdminLayoutDashboardAccountsRoute,
    AuthAdminLayoutDashboardEnergyRoute: AuthAdminLayoutDashboardEnergyRoute,
    AuthAdminLayoutDashboardMaintenanceRoute:
      AuthAdminLayoutDashboardMaintenanceRoute,
    AuthAdminLayoutDashboardProcurementRoute:
      AuthAdminLayoutDashboardProcurementRoute,
    AuthAdminLayoutDashboardProductionRoute:
      AuthAdminLayoutDashboardProductionRoute,
    AuthAdminLayoutDashboardQcRoute: AuthAdminLayoutDashboardQcRoute,
    AuthAdminLayoutDashboardSalesRoute: AuthAdminLayoutDashboardSalesRoute,
    AuthAdminLayoutDashboardTradingRoute: AuthAdminLayoutDashboardTradingRoute,
    AuthAdminLayoutDashboardWorkforceRoute:
      AuthAdminLayoutDashboardWorkforceRoute,
    AuthAdminLayoutDashboardIndexRoute: AuthAdminLayoutDashboardIndexRoute,
  }

const AuthAdminLayoutDashboardRouteWithChildren =
  AuthAdminLayoutDashboardRoute._addFileChildren(
    AuthAdminLayoutDashboardRouteChildren,
  )

interface AuthAdminLayoutRouteChildren {
  AuthAdminLayoutDashboardRoute: typeof AuthAdminLayoutDashboardRouteWithChildren
  AuthAdminLayoutProfileIndexRoute: typeof AuthAdminLayoutProfileIndexRoute
  AuthAdminLayoutProfileLogIndexRoute: typeof AuthAdminLayoutProfileLogIndexRoute
  AuthAdminLayoutProfileSettingsIndexRoute: typeof AuthAdminLayoutProfileSettingsIndexRoute
  AuthAdminLayoutProfileUsersIndexRoute: typeof AuthAdminLayoutProfileUsersIndexRoute
}

const AuthAdminLayoutRouteChildren: AuthAdminLayoutRouteChildren = {
  AuthAdminLayoutDashboardRoute: AuthAdminLayoutDashboardRouteWithChildren,
  AuthAdminLayoutProfileIndexRoute: AuthAdminLayoutProfileIndexRoute,
  AuthAdminLayoutProfileLogIndexRoute: AuthAdminLayoutProfileLogIndexRoute,
  AuthAdminLayoutProfileSettingsIndexRoute:
    AuthAdminLayoutProfileSettingsIndexRoute,
  AuthAdminLayoutProfileUsersIndexRoute: AuthAdminLayoutProfileUsersIndexRoute,
}

const AuthAdminLayoutRouteWithChildren = AuthAdminLayoutRoute._addFileChildren(
  AuthAdminLayoutRouteChildren,
)

interface AuthAdminRouteChildren {
  AuthAdminLayoutRoute: typeof AuthAdminLayoutRouteWithChildren
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminLayoutRoute: AuthAdminLayoutRouteWithChildren,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthUserLayoutDashboardRouteChildren {
  AuthUserLayoutDashboardAccountsRoute: typeof AuthUserLayoutDashboardAccountsRoute
  AuthUserLayoutDashboardEnergyRoute: typeof AuthUserLayoutDashboardEnergyRoute
  AuthUserLayoutDashboardMaintenanceRoute: typeof AuthUserLayoutDashboardMaintenanceRoute
  AuthUserLayoutDashboardProcurementRoute: typeof AuthUserLayoutDashboardProcurementRoute
  AuthUserLayoutDashboardProductionRoute: typeof AuthUserLayoutDashboardProductionRoute
  AuthUserLayoutDashboardQcRoute: typeof AuthUserLayoutDashboardQcRoute
  AuthUserLayoutDashboardSalesRoute: typeof AuthUserLayoutDashboardSalesRoute
  AuthUserLayoutDashboardTradingRoute: typeof AuthUserLayoutDashboardTradingRoute
  AuthUserLayoutDashboardWorkforceRoute: typeof AuthUserLayoutDashboardWorkforceRoute
  AuthUserLayoutDashboardIndexRoute: typeof AuthUserLayoutDashboardIndexRoute
}

const AuthUserLayoutDashboardRouteChildren: AuthUserLayoutDashboardRouteChildren =
  {
    AuthUserLayoutDashboardAccountsRoute: AuthUserLayoutDashboardAccountsRoute,
    AuthUserLayoutDashboardEnergyRoute: AuthUserLayoutDashboardEnergyRoute,
    AuthUserLayoutDashboardMaintenanceRoute:
      AuthUserLayoutDashboardMaintenanceRoute,
    AuthUserLayoutDashboardProcurementRoute:
      AuthUserLayoutDashboardProcurementRoute,
    AuthUserLayoutDashboardProductionRoute:
      AuthUserLayoutDashboardProductionRoute,
    AuthUserLayoutDashboardQcRoute: AuthUserLayoutDashboardQcRoute,
    AuthUserLayoutDashboardSalesRoute: AuthUserLayoutDashboardSalesRoute,
    AuthUserLayoutDashboardTradingRoute: AuthUserLayoutDashboardTradingRoute,
    AuthUserLayoutDashboardWorkforceRoute:
      AuthUserLayoutDashboardWorkforceRoute,
    AuthUserLayoutDashboardIndexRoute: AuthUserLayoutDashboardIndexRoute,
  }

const AuthUserLayoutDashboardRouteWithChildren =
  AuthUserLayoutDashboardRoute._addFileChildren(
    AuthUserLayoutDashboardRouteChildren,
  )

interface AuthUserLayoutRouteChildren {
  AuthUserLayoutDashboardRoute: typeof AuthUserLayoutDashboardRouteWithChildren
  AuthUserLayoutProfileIndexRoute: typeof AuthUserLayoutProfileIndexRoute
  AuthUserLayoutProfileSettingsIndexRoute: typeof AuthUserLayoutProfileSettingsIndexRoute
}

const AuthUserLayoutRouteChildren: AuthUserLayoutRouteChildren = {
  AuthUserLayoutDashboardRoute: AuthUserLayoutDashboardRouteWithChildren,
  AuthUserLayoutProfileIndexRoute: AuthUserLayoutProfileIndexRoute,
  AuthUserLayoutProfileSettingsIndexRoute:
    AuthUserLayoutProfileSettingsIndexRoute,
}

const AuthUserLayoutRouteWithChildren = AuthUserLayoutRoute._addFileChildren(
  AuthUserLayoutRouteChildren,
)

interface AuthUserRouteChildren {
  AuthUserLayoutRoute: typeof AuthUserLayoutRouteWithChildren
  AuthUserIndexRoute: typeof AuthUserIndexRoute
}

const AuthUserRouteChildren: AuthUserRouteChildren = {
  AuthUserLayoutRoute: AuthUserLayoutRouteWithChildren,
  AuthUserIndexRoute: AuthUserIndexRoute,
}

const AuthUserRouteWithChildren = AuthUserRoute._addFileChildren(
  AuthUserRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthUserRoute: AuthUserRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  AuthIndexRoute: AuthIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
